// Generated by gencpp from file hello/service.msg
// DO NOT EDIT!


#ifndef HELLO_MESSAGE_SERVICE_H
#define HELLO_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <hello/serviceRequest.h>
#include <hello/serviceResponse.h>


namespace hello
{

struct service
{

typedef serviceRequest Request;
typedef serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service
} // namespace hello


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello::service > {
  static const char* value()
  {
    return "95f338c03e3160910deaf2a8b3b2fb2c";
  }

  static const char* value(const ::hello::service&) { return value(); }
};

template<>
struct DataType< ::hello::service > {
  static const char* value()
  {
    return "hello/service";
  }

  static const char* value(const ::hello::service&) { return value(); }
};


// service_traits::MD5Sum< ::hello::serviceRequest> should match 
// service_traits::MD5Sum< ::hello::service > 
template<>
struct MD5Sum< ::hello::serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello::service >::value();
  }
  static const char* value(const ::hello::serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello::serviceRequest> should match 
// service_traits::DataType< ::hello::service > 
template<>
struct DataType< ::hello::serviceRequest>
{
  static const char* value()
  {
    return DataType< ::hello::service >::value();
  }
  static const char* value(const ::hello::serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello::serviceResponse> should match 
// service_traits::MD5Sum< ::hello::service > 
template<>
struct MD5Sum< ::hello::serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello::service >::value();
  }
  static const char* value(const ::hello::serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello::serviceResponse> should match 
// service_traits::DataType< ::hello::service > 
template<>
struct DataType< ::hello::serviceResponse>
{
  static const char* value()
  {
    return DataType< ::hello::service >::value();
  }
  static const char* value(const ::hello::serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_MESSAGE_SERVICE_H
