// Generated by gencpp from file hello/serviceResponse.msg
// DO NOT EDIT!


#ifndef HELLO_MESSAGE_SERVICERESPONSE_H
#define HELLO_MESSAGE_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello
{
template <class ContainerAllocator>
struct serviceResponse_
{
  typedef serviceResponse_<ContainerAllocator> Type;

  serviceResponse_()
    : output_res1(0)
    , outout_res2(0)  {
    }
  serviceResponse_(const ContainerAllocator& _alloc)
    : output_res1(0)
    , outout_res2(0)  {
  (void)_alloc;
    }



   typedef int32_t _output_res1_type;
  _output_res1_type output_res1;

   typedef int32_t _outout_res2_type;
  _outout_res2_type outout_res2;





  typedef boost::shared_ptr< ::hello::serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello::serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct serviceResponse_

typedef ::hello::serviceResponse_<std::allocator<void> > serviceResponse;

typedef boost::shared_ptr< ::hello::serviceResponse > serviceResponsePtr;
typedef boost::shared_ptr< ::hello::serviceResponse const> serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello::serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello::serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hello': ['/home/luca/test_ws1/src/hello/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello::serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello::serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello::serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello::serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello::serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello::serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello::serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed2aac0cbe0c2dcea81d62a239d7ad9f";
  }

  static const char* value(const ::hello::serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed2aac0cbe0c2dceULL;
  static const uint64_t static_value2 = 0xa81d62a239d7ad9fULL;
};

template<class ContainerAllocator>
struct DataType< ::hello::serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello/serviceResponse";
  }

  static const char* value(const ::hello::serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello::serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 output_res1\n\
int32 outout_res2\n\
\n\
";
  }

  static const char* value(const ::hello::serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello::serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_res1);
      stream.next(m.outout_res2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello::serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello::serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "output_res1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.output_res1);
    s << indent << "outout_res2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.outout_res2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_MESSAGE_SERVICERESPONSE_H
