// Generated by gencpp from file hello/serviceRequest.msg
// DO NOT EDIT!


#ifndef HELLO_MESSAGE_SERVICEREQUEST_H
#define HELLO_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello
{
template <class ContainerAllocator>
struct serviceRequest_
{
  typedef serviceRequest_<ContainerAllocator> Type;

  serviceRequest_()
    : input_req1(0)
    , input_req2(0.0)  {
    }
  serviceRequest_(const ContainerAllocator& _alloc)
    : input_req1(0)
    , input_req2(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _input_req1_type;
  _input_req1_type input_req1;

   typedef float _input_req2_type;
  _input_req2_type input_req2;





  typedef boost::shared_ptr< ::hello::serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello::serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct serviceRequest_

typedef ::hello::serviceRequest_<std::allocator<void> > serviceRequest;

typedef boost::shared_ptr< ::hello::serviceRequest > serviceRequestPtr;
typedef boost::shared_ptr< ::hello::serviceRequest const> serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello::serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello::serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hello': ['/home/luca/test_ws1/src/hello/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello::serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello::serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello::serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello::serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello::serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello::serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03f75188953b9a3a4c297b467ba17420";
  }

  static const char* value(const ::hello::serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03f75188953b9a3aULL;
  static const uint64_t static_value2 = 0x4c297b467ba17420ULL;
};

template<class ContainerAllocator>
struct DataType< ::hello::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello/serviceRequest";
  }

  static const char* value(const ::hello::serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 input_req1\n\
float32 input_req2\n\
";
  }

  static const char* value(const ::hello::serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello::serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_req1);
      stream.next(m.input_req2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello::serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello::serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_req1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input_req1);
    s << indent << "input_req2: ";
    Printer<float>::stream(s, indent + "  ", v.input_req2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_MESSAGE_SERVICEREQUEST_H
